### ISSUE TITLE
Move all tests into the test suite

### ISSUE THREAD

**Issue by cies** [HugoDaniel/timerep#11]
The `testParse` function and other test-related functions in the primary source of the package could go to the test suite. Maybe that also justifies to base the test suite on something like [tasty](https://github.com/feuerbach/tasty).

**Comment by k0ral** [comment]
I'm working on that, I'll make a pull request soon.

**Comment by k0ral** [comment]
Done in #15 .

**Comment by cies** [comment]
@k0ral: thanks! looks good.
