### ISSUE TITLE
Please consider registering this package to Stackage

### ISSUE THREAD

**Issue by cies** [HugoDaniel/timerep#13]
Stackage a set of Haskell packages that is known to compile together. I'd like to use `timerep` as a dependency on [htoml](https://github.com/cies/htoml), and register it on Stackage; but I cannot do both when your package is not already registered.

Thanks for considering!

**Comment by k0ral** [comment]
Ongoing in https://github.com/fpco/stackage/pull/656 .

**Comment by k0ral** [comment]
Done.

**Comment by cies** [comment]
Cheers!
