### ISSUE TITLE
Cabal Install error with GHC 7.4.2 on Mac 10.7

### ISSUE THREAD

**Issue by tatac1** [HugoDaniel/timerep#2]
Hi Hugo

I got the error message when installing,

Resolving dependencies...
Configuring rfc3339-1.0.4...
Preprocessing library rfc3339-1.0.4...
Building rfc3339-1.0.4...
[1 of 1] Compiling Data.Time.RFC3339 ( Data/Time/RFC3339.hs, dist/build/Data/Time/RFC3339.o )

Data/Time/RFC3339.hs:60:10:
    Illegal instance declaration for `RFC3339 String'
      (All instance types must be of the form (T a1 ... an)
       where a1 ... an are *distinct type variables*,
       and each type variable appears at most once in the instance head.
       Use -XFlexibleInstances if you want to disable this.)
    In the instance declaration for `RFC3339 String'
cabal: Error: some packages failed to install:
rfc3339-1.0.4 failed during the building phase. The exception was:
ExitFailure 1

I have confirm  " {-# LANGUAGE TypeSynonymInstances, FlexibleInstances #-}"  in the RFC3339.hs, it's no wired...

How can i solve it?

**Comment by k0ral** [comment]
Closed since it's about a deprecated package using an unsupported GHC version.
